"""
NBA Bet Analyzer (With 'Lean' Logic)

Interactive tool that compares your model's predictions against Sportsbook lines.
Includes 'Strong Bet', 'Lean', and 'Pass' recommendations.
"""

import json
import os
import sys

# Color codes for terminal output
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
RESET = "\033[0m"

def load_predictions(filename="nba_predictions.json"):
    """Load the latest predictions generated by the pipeline."""
    if not os.path.exists(filename):
        print(f"{RED}Error: {filename} not found.{RESET}")
        print("Please run prediction_pipeline.py first to generate data.")
        sys.exit(1)
        
    with open(filename, 'r') as f:
        return json.load(f)

def get_float_input(prompt):
    """Safely get float/int input from user."""
    while True:
        try:
            user_input = input(prompt).strip()
            # Handle empty input
            if not user_input:
                continue
            return float(user_input)
        except ValueError:
            print(f"{RED}Invalid number. Please try again.{RESET}")

def convert_american_to_decimal(american_odds):
    """
    Convert American (Vegas) odds to Decimal odds.
    Ex: -110 -> 1.91
    Ex: +150 -> 2.50
    """
    if american_odds > 0:
        return 1 + (american_odds / 100)
    else:
        return 1 + (100 / abs(american_odds))

def analyze_bet(target, prediction, mae, line, vegas_odds):
    """Core logic: Compare Edge vs MAE with 'Lean' threshold."""
    
    # Convert odds
    decimal_odds = convert_american_to_decimal(vegas_odds)
    implied_prob = (1 / decimal_odds) * 100
    
    print(f"\n{CYAN}--- ANALYZING {target} ---{RESET}")
    print(f"Model Prediction: {GREEN}{prediction:.1f}{RESET}")
    print(f"Model Error (MAE): {YELLOW}{mae:.2f}{RESET}")
    print(f"Vegas Line:       {CYAN}{line:.1f}{RESET} ({vegas_odds})")
    print(f"Break-Even Win %: {YELLOW}{implied_prob:.1f}%{RESET}")
    
    # 1. Calculate the Edge
    edge = prediction - line
    abs_edge = abs(edge)
    
    # 2. Determine Direction
    direction = "OVER" if edge > 0 else "UNDER"
    
    # 3. Decision Logic
    # STRONG: Edge > 100% of MAE
    # LEAN:   Edge > 80% of MAE
    
    strong_threshold = mae * 1.0
    lean_threshold = mae * 0.8
    
    print("-" * 30)
    print(f"Projected Edge:   {abs_edge:.2f} points")
    print("-" * 30)

    if abs_edge > strong_threshold:
        # Strong Bet
        print(f"{GREEN}✅ RECOMMENDATION: BET {direction} {line}{RESET}")
        print(f"   (Edge covers 100% of error margin. Full unit play.)")
        
    elif abs_edge > lean_threshold:
        # Lean / Soft Bet
        percent_of_mae = (abs_edge / mae) * 100
        print(f"{YELLOW}⚠️ RECOMMENDATION: LEAN {direction} {line}{RESET}")
        print(f"   (Edge covers {percent_of_mae:.0f}% of error margin.)")
        print(f"   tradable, but consider smaller sizing.")
        
    else:
        # Pass
        print(f"{RED}❌ RECOMMENDATION: PASS{RESET}")
        print(f"   (Edge is only {abs_edge:.1f} points. Too much noise.)")

def main():
    print(f"{CYAN}========================================{RESET}")
    print(f"{CYAN}   NBA BET ANALYZER - DECISION ENGINE   {RESET}")
    print(f"{CYAN}========================================{RESET}")

    data = load_predictions()
    player = data.get('player', 'Unknown')
    print(f"Loaded data for: {GREEN}{player}{RESET}")
    
    preds = data.get('predictions', {})
    maes = data.get('mae_scores', {})
    
    # Default MAEs based on your latest successful run
    default_maes = {
        'PTS': 5.73, 
        'REB': 3.10, 
        'AST': 1.88, 
        'STL': 0.56, 
        'BLK': 0.67, 
        'PRA': 6.88
    }

    while True:
        print(f"\nAvailable Targets: {', '.join(preds.keys())}")
        target = input("Enter Target to Analyze (or 'q' to quit): ").upper()
        
        if target == 'Q':
            break
            
        if target not in preds:
            print(f"{RED}Target '{target}' not found in predictions.{RESET}")
            continue
            
        # Get Model Data
        prediction = preds[target]
        mae = maes.get(target, default_maes.get(target, 0.0))

        # Get User Data
        line = get_float_input(f"Enter Sportsbook Line for {target} (e.g. 25.5): ")
        vegas_odds = get_float_input(f"Enter Vegas Odds (e.g. -110 or +120): ")

        # Run Analysis
        analyze_bet(target, prediction, mae, line, vegas_odds)

if __name__ == "__main__":
    main()